const catFacts = [
    "Cats have a special reflective layer behind their retinas called the tapetum lucidum, which enhances their night vision.",
    "A group of cats is called a clowder.",
    "A cat's nose has a unique pattern, much like a human fingerprint.",
    "Cats spend about 70% of their lives sleeping.",
    "The average cat sleeps for about 13-14 hours a day.",
    "Cats have five toes on their front paws but only four on their back paws.",
    "Cats have a specialized collarbone that allows them to always land on their feet when they fall.",
    "Cats can rotate their ears 180 degrees.",
    "The world's oldest cat lived to be 38 years old.",
    "Cats have over 20 muscles in their ears alone, allowing for a wide range of movements.",
    "A cat's whiskers are roughly as wide as its body, allowing them to judge whether they can fit through a space.",
    "Cats have a specialized grooming tool on their tongue called papillae, which are small, backward-facing barbs.",
    "A cat's purr can range between 25 and 150 Hertz, which is believed to have therapeutic effects.",
    "Cats have a powerful sense of smell, with around 200 million odor sensors in their nasal cavity.",
    "Cats can make over 100 different sounds, while dogs can only make about 10.",
    "The heaviest domestic cat on record weighed 46 pounds.",
    "The record for the longest domestic cat is over four feet long.",
    "Cats are crepuscular, which means they are most active during dawn and dusk.",
    "Cats have a unique grooming behavior called allogrooming, where they groom each other as a form of social bonding.",
    "Cats' whiskers are also sensitive to air currents, helping them navigate in the dark.",
    "A cat's brain is 90% similar to a human's, making them quite intelligent animals.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats have retractable claws, which they can extend and retract as needed.",
    "A cat can jump up to six times its body length in one leap.",
    "Cats have a specialized collarbone that allows them to squeeze through tight spaces.",
    "The world's largest cat measured 48.5 inches in length.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a unique walking style called the \"direct registering\" gait, where they step with both front and back paws on the same side moving together.",
    "Cats' noses are unique, with patterns like fingerprints.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats are obligate carnivores, which means they need meat to survive.",
    "Cats have a body temperature between 100.5 to 102.5 degrees Fahrenheit.",
    "Cats have five toes on their front paws and four on their back paws, but some cats may have extra toes due to a genetic mutation, known as polydactylism.",
    "A cat's heart beats nearly twice as fast as a human heart, averaging between 150-200 beats per minute.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have a grooming behavior called \"bunting,\" where they rub their faces against objects to mark them with their scent glands.",
    "Cats have a strong territorial instinct and may spray urine to mark their territory.",
    "Cats can't taste sweetness due to the lack of sweet receptors in their taste buds.",
    "Cats' pupils can dilate and contract rapidly, allowing them to adjust to changes in light quickly.",
    "Cats have an average of 24 whiskers arranged in four horizontal rows on each side of their face.",
    "Cats have a specialized collarbone that allows them to squeeze through tight spaces.",
    "Cats' whiskers are roughly as wide as their bodies, allowing them to gauge whether they can fit through a space.",
    "Cats have a specialized grooming tool on their tongue called papillae, which are small, backward-facing barbs.",
    "Cats' purrs have been shown to have therapeutic effects, including reducing stress and anxiety in humans.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats can rotate their ears independently up to 180 degrees.",
    "Cats have a unique walking style called \"direct registering,\" where they move both front and back legs on the same side of the body at the same time.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats' whiskers can detect changes in air currents, helping them navigate in the dark.",
    "Cats can jump up to six times their body length in one leap.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have retractable claws, which they can extend and retract as needed.",
    "Cats have a powerful sense of smell, with around 200 million odor sensors in their nasal cavity.",
    "Cats have a unique grooming behavior called allogrooming, where they groom each other as a form of social bonding.",
    "Cats' purrs have been shown to have therapeutic effects, including reducing stress and anxiety in humans.",
    "Cats can rotate their ears independently up to 180 degrees.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats' whiskers can detect changes in air currents, helping them navigate in the dark.",
    "Cats can jump up to six times their body length in one leap.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have retractable claws, which they can extend and retract as needed.",
    "Cats have a powerful sense of smell, with around 200 million odor sensors in their nasal cavity.",
    "Cats have a unique grooming behavior called allogrooming, where they groom each other as a form of social bonding.",
    "Cats' purrs have been shown to have therapeutic effects, including reducing stress and anxiety in humans.",
    "Cats can rotate their ears independently up to 180 degrees.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats' whiskers can detect changes in air currents, helping them navigate in the dark.",
    "Cats can jump up to six times their body length in one leap.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have retractable claws, which they can extend and retract as needed.",
    "Cats have a powerful sense of smell, with around 200 million odor sensors in their nasal cavity.",
    "Cats have a unique grooming behavior called allogrooming, where they groom each other as a form of social bonding.",
    "Cats' purrs have been shown to have therapeutic effects, including reducing stress and anxiety in humans.",
    "Cats can rotate their ears independently up to 180 degrees.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats' whiskers can detect changes in air currents, helping them navigate in the dark.",
    "Cats can jump up to six times their body length in one leap.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have retractable claws, which they can extend and retract as needed.",
    "Cats have a powerful sense of smell, with around 200 million odor sensors in their nasal cavity.",
    "Cats have a unique grooming behavior called allogrooming, where they groom each other as a form of social bonding.",
    "Cats' purrs have been shown to have therapeutic effects, including reducing stress and anxiety in humans.",
    "Cats can rotate their ears independently up to 180 degrees.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats' whiskers can detect changes in air currents, helping them navigate in the dark.",
    "Cats can jump up to six times their body length in one leap.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have retractable claws, which they can extend and retract as needed.",
    "Cats have a powerful sense of smell, with around 200 million odor sensors in their nasal cavity.",
    "Cats have a unique grooming behavior called allogrooming, where they groom each other as a form of social bonding.",
    "Cats' purrs have been shown to have therapeutic effects, including reducing stress and anxiety in humans.",
    "Cats can rotate their ears independently up to 180 degrees.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats' whiskers can detect changes in air currents, helping them navigate in the dark.",
    "Cats can jump up to six times their body length in one leap.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have retractable claws, which they can extend and retract as needed.",
    "Cats have a powerful sense of smell, with around 200 million odor sensors in their nasal cavity.",
    "Cats have a unique grooming behavior called allogrooming, where they groom each other as a form of social bonding.",
    "Cats' purrs have been shown to have therapeutic effects, including reducing stress and anxiety in humans.",
    "Cats can rotate their ears independently up to 180 degrees.",
    "Cats have a third eyelid called the haw, which helps protect their eyes and keep them moist.",
    "Cats have a specialized scent organ on the roof of their mouths called the Jacobson's organ, which allows them to \"taste\" scents.",
    "Cats groom themselves to regulate body temperature and stimulate blood flow.",
    "Cats have scent glands on their cheeks, forehead, and lips, which they use to mark their territory.",
    "Cats' whiskers can detect changes in air currents, helping them navigate in the dark.",
    "Cats can jump up to six times their body length in one leap.",
    "Cats have a keen sense of balance, which helps them land on their feet.",
    "Cats have a flexible spine that allows them to twist their bodies in mid-air.",
    "Cats have retractable claws, which they can extend and retract as needed."
]

const list = document.querySelectorAll('li')
function randomFact() {
    // Using For of
    for (li of list) {
        li.innerText = catFacts[Math.floor(Math.random() * catFacts.length)]
    }
}

document.querySelector('.btn').addEventListener('click', randomFact)
window.addEventListener('load', randomFact)
window.addEventListener('keydown', (e) => {
    e.preventDefault()
    if (e.keyCode === 32) {
        randomFact()
    } else return;
})